name: env-test
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.16=py39h0962b89_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.3=h982b769_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh92f572d_0
  - ipython=8.18.1=pyh707e725_3
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - krb5=1.21.3=h237132a_0
  - libcxx=20.1.8=hd7fd590_1
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libffi=3.4.4=hca03da5_1
  - libsodium=1.0.20=h99b78c6_0
  - libzlib=1.3.1=h5f15de7_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.3=pyhc872135_0
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=5.8.0=py39h5161555_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.9.25=he39995d_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.9=2_cp39
  - pyzmq=27.1.0=py39h854a7ef_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py39hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=hab6afd1_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.1=py39h80987f9_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h04d1e81_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py39hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - filelock==3.19.1
      - fsspec==2025.10.0
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==2.0.2
      - pillow==11.3.0
      - sympy==1.14.0
      - torch==2.8.0
      - torchvision==0.23.0
prefix: /opt/anaconda3/envs/env-test
